'use client'

import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "./globals.css";
import Register from './../../component/Register';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <SessionProvider>
        <body suppressHydrationWarning={true}>
          {children}

        </body>
      </SessionProvider>
    </html>
  );
}
